import { type NextPage } from "next";
import Head from "next/head";
import type { NextPageWithLayout } from './_app'
import type { ReactElement } from 'react'
import Layout from '../components/layout'
import { StaticImageData } from "next/image";
import Image from "next/image";

import SectionVideo from "../components/sections/SectionVideo";
import SectionSponsors from "../components/sections/SectionSponsors";
import SectionTracks from "../components/sections/SectionTracks";
import SectionMedia from "../components/sections/SectionMedia";
import SectionArtists from "../components/sections/SectionArtists";
import SectionFooter from "../components/sections/SectionFooter";


interface PageProps {
  tracks: [
    {
      id: string;
      title: string;
      artist: string;
      audioSrc: string;
      image: StaticImageData;
    }
  ];
}

const Page: NextPageWithLayout<PageProps> = ({ tracks }) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section id="hero">
        <SectionVideo />
      </section>

      <section id="sponsors">
        <SectionSponsors />
      </section>

      <section id="tracks">
        <SectionTracks tracks={tracks} />
      </section>

      <section id="socialmedia">
        <SectionMedia />
      </section>

      <section id="artists">
        <SectionArtists />
      </section>

      <section id="footer">
        <SectionFooter />
      </section>

    </>
  );
};

Page.getLayout = function getLayout(page: ReactElement) {
  return (
    <Layout>
      {page}
    </Layout>
  )
}

export async function getStaticProps() {
  const res = await fetch("http://localhost:3000/api/tracks");
  const tracks = await res.json();

  return {
    props: {
      tracks,
    },
  };
}

export default Page;
